spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: productServiceCircuitBreaker
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/inventory/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: inventoryServiceCircuitBreaker
            - id: billing-service
              uri: lb://billing-service
              predicates:
                - Path=/orders/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: billingServiceCircuitBreaker
            - id: analytics-service
              uri: lb://analytics-service
              predicates:
                - Path=/analytics/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: analyticsServiceCircuitBreaker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/retailforge/protocol/openid-connect/certs
  threads:
    virtual:
      enabled: false


springdoc:
  swagger-ui:
    enabled: true
    oauth:
      clientId: retailforge-api-gateway
      clientSecret: wwUCtFsgR4rEKMnf2eiZOccU2rBQTT1w
      realm: retailforge
      appName: API Gateway Swagger UI
      usePkceWithAuthorizationCodeGrant: true
    urls:
      - name: Product Service
        url: /products/v3/api-docs
      - name: Inventory Service
        url: /inventory/v3/api-docs
      - name: Billing Service
        url: /orders/v3/api-docs
      - name: Analytics Service
        url: /analytics/v3/api-docs

