spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/inventory/**
            - id: billing-service
              uri: lb://billing-service
              predicates:
                - Path=/orders/**
            - id: analytics-service
              uri: lb://analytics-service
              predicates:
                - Path=/analytics/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/retailforge/protocol/openid-connect/certs
