spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted.packages: "*"
            type.mapping: "com.retailforge.event.PaymentCompletedEvent:com.retailforge.event.PaymentCompletedEvent,com.retailforge.event.LowStockAlertEvent:com.retailforge.event.LowStockAlertEvent"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NOTIFICATION_GMAIL_USERNAME:placeholder_email@gmail.com}
    password: ${NOTIFICATION_GMAIL_PASSWORD:placeholder_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
