server:
  port: 8084

spring:
  application:
    name: billing-service
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/retailforge/protocol/openid-connect/certs

